### ISSUE TITLE
Why at least 4 images?

### ISSUE THREAD

**Issue by DenisFromRussia** [pengsongyou/SRmeetsPS#1]
Hi, thanks for your paper and code. I am currently trying to use it for my work but i can't understand why do we need exactly 4 or more images for the input - it seems that it don't derives from the math part of the paper or am i wrong?

**Comment by BjoernHaefner** [comment]
Hi, for photometric stereo three or more images are necessary to determine surface orientation uniquely (see Woodham, R.J. 1980. Photometric method for determining surface orientation from multiple images. Optical Engineerings 19, I, 139-144). As super-resolution is another ill-posed problem, multiple image observations are needed as well. For a scaling factor of s, we have s^2 times more pixels in the super-resolution image, thus if the scaling factor is s=2 the number of input images should be at least 4 in order to avoid an under determined system of equations. For a scaling factor of 4 or larger we didn't notice an effect of deterioration if n<=4^2=16, nevertheless to be on the safe side at least four images should be chosen.
